# Generated by Django 4.2 on 2023-04-11 23:08

from django.db import migrations, models
import django.db.models.deletion
import vemsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_desc', models.CharField(max_length=50)),
                ('event_file', models.FileField(blank=True, null=True, upload_to=vemsapp.models.getfilename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('events_years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vemsapp.events_year')),
            ],
        ),
    ]
