# Generated by Django 4.2 on 2023-04-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0002_upload_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events_year',
            table='years',
        ),
        migrations.AlterModelTable(
            name='upload_event',
            table='events',
        ),
    ]
