# Generated by Django 4.2 on 2023-04-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0004_eventdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='eventdetails',
            new_name='addevents',
        ),
    ]
