# Generated by Django 4.2 on 2023-04-14 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0007_eventdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventregisteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('college_name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eventreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vemsapp.addevents')),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
