# Generated by Django 4.2 on 2023-04-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0008_eventregisteration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventdetails',
            table='eventdetail',
        ),
    ]
