# Generated by Django 4.2 on 2023-04-18 00:16

from django.db import migrations, models
import vemsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0010_alter_eventregisteration_eventreg'),
    ]

    operations = [
        migrations.CreateModel(
            name='addevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('last_date', models.DateField()),
                ('auditorium', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
                ('small_desc', models.CharField(max_length=450)),
                ('desc', models.CharField(max_length=1000)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to=vemsapp.models.getfilename)),
                ('event_img', models.ImageField(blank=True, null=True, upload_to=vemsapp.models.getfilename)),
                ('invitation', models.FileField(blank=True, null=True, upload_to=vemsapp.models.getfilename)),
                ('latest_event', models.BooleanField(default=False, help_text='o-default,1-Trending')),
                ('status', models.BooleanField(default=False, help_text='o-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
