# Generated by Django 4.2 on 2023-04-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0011_addevent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addevent',
            table='addevent',
        ),
    ]
