# Generated by Django 4.2 on 2023-04-18 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0012_alter_addevent_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('rollno', models.CharField(max_length=50)),
                ('collegename', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eventname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vemsapp.addevent')),
            ],
            options={
                'db_table': 'registerevent',
            },
        ),
    ]
