# Generated by Django 4.2 on 2023-04-18 17:01

from django.db import migrations, models
import vemsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0014_event_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerevent',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=vemsapp.models.getfilename),
        ),
    ]
