# Generated by Django 4.2 on 2023-04-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0016_event_announcement_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_announcement',
            name='status',
            field=models.BooleanField(default=False, help_text='o-show,1-hidden'),
        ),
    ]
