# Generated by Django 4.2 on 2023-04-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vemsapp', '0017_event_announcement_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event_announcement',
            table='eventannouncement',
        ),
    ]
